### ISSUE TITLE
Cannot set several fields

### ISSUE THREAD

**Issue by adelevie** [18F/iaa-gem#6]

**Comment by adelevie** [comment]
See: 

#### 7600A:
- [x] https://github.com/18F/iaa-gem/issues/5 - number_of_days_this_iaa_may_be_terminated
- [x] https://github.com/18F/iaa-gem/issues/4 - general_explanation_overhead_fees_and_charges
- [x] https://github.com/18F/iaa-gem/issues/3 - gt_and_c_number

#### 7600B:
- [x] https://github.com/18F/iaa-gem/issues/8 - gt_and_c_number
- [x] https://github.com/18F/iaa-gem/issues/9 - requesting_agency_a
- [x] https://github.com/18F/iaa-gem/issues/10 - servicing_agency_a
- [x] https://github.com/18F/iaa-gem/issues/11 - overhead_fees_and_charges

There are pending (failing) specs for each of these in `spec/form_7600a_spec.rb` and `spec/form_7600b_spec.rb`.

**Comment by adelevie** [comment]
Changes for @joshuabailes:

#### 7600A:
- "No. of days this IAA may be terminated" => "Number of days this IAA may be terminated"
- "General Explanation Overhead Fees &amp; Charges" => "general explanation overhead fees and charges"
- "GT&amp;C #" => "GT and C number"

#### 7600B:
- "GT&amp;C #" => "GT and C number"
- overhead_fees_and_charges

##### Other problem fields in 7600B

For some reason, these fields truncate the input by one character: 
- "Requesting Agency A"
- "Servicing Agency B"

**Comment by adelevie** [comment]
All of these are fixed by https://github.com/18F/iaa-gem/pull/28.
